site_name: Biology Problems OER
docs_dir: site_docs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.footer

markdown_extensions:
- attr_list

plugins:
- search
- include-markdown

extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/scripts/custom.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vosslab
      name: GitHub
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/neilvosslab
      name: YouTube
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/neilvosslab.bsky.social
      name: Bluesky
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vosslab
      name: LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/neilvosslab
      name: Facebook
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/vosslab
      name: Patreon
    - icon: fontawesome/brands/paypal
      link: https://paypal.me/vosslab
      name: PayPal
  generator: false

copyright: >
  &copy; 2024-2025 Dr. Neil Voss â€¢ Licensed under
  <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">
    CC BY-SA 4.0
    <i class="fa-brands fa-creative-commons"></i>
    <i class="fa-brands fa-creative-commons-by"></i>
    <i class="fa-brands fa-creative-commons-sa"></i>
  </a>

nav:
- "<i class='fa fa-home'></i> Home": index.md
- "<i class='fa fa-puzzle-piece'></i> Daily Puzzles":
  - "<i class='fa fa-dice-five'></i> Peptidyle": daily_puzzles/peptidyle.md
  - "<i class='fa fa-dna'></i> Deletion mutants": daily_puzzles/deletion_mutants.md
- "ðŸ§ª Biochemistry":
  - 'List of Topics': biochemistry/index.md
  - '1: Life Molecules': biochemistry/topic01/index.md
  - '2: Water and pH': biochemistry/topic02/index.md
  - '3: Amino Acids': biochemistry/topic03/index.md
  - '4: Protein Structure': biochemistry/topic04/index.md
  - '5: Protein Purification': biochemistry/topic05/index.md
  - '6: Thermodynamics': biochemistry/topic06/index.md
  - '7: Enzyme Kinetics': biochemistry/topic07/index.md
  - '8: Enzyme Regulation': biochemistry/topic08/index.md
  - '9: Carbohydrates': biochemistry/topic09/index.md
  - '10: Nucleic Acids': biochemistry/topic10/index.md
  - '11: Human Senses': biochemistry/topic11/index.md
- "ðŸª° Genetics":
  - 'List of Topics': genetics/index.md
  - '1: Genetic Disorders': genetics/topic01/index.md
  - '2: DNA Structure': genetics/topic02/index.md
  - '3: DNA Profiling': genetics/topic03/index.md
  - '4: Mendelian Genetics': genetics/topic04/index.md
  - '5: Gene Interactions': genetics/topic05/index.md
  - '6: Chromosomal Inheritance': genetics/topic06/index.md
  - '7: Chi Square Analysis': genetics/topic07/index.md
  - '8: Gene Mapping': genetics/topic08/index.md
  - '9: Chromosomal Disorders': genetics/topic09/index.md
  - '10: Population Genetics': genetics/topic10/index.md
  - '11: Gene Trees': genetics/topic11/index.md
- "ðŸ§¬ Molecular Biology": molecular_biology/index.md
- "ðŸŽ² Biostatistics": biostatistics/index.md
- "<i class='fa fa-book-open'></i> Tutorials":
  - 'List of Tutorials': tutorials/index.md
  - "<i class='fa fa-chalkboard'></i> Blackboard BBQ Text File Upload": tutorials/bbq_tutorial.md
  - "<i class='fa fa-chalkboard'></i> Blackboard Ultra QTI .zip Import Guide": tutorials/bbq_ultra_tutorial.md
  - "<i class='fa fa-chalkboard'></i> Canvas QTI .zip Import Guide": tutorials/canvas_tutorial.md
- "<i class='fa fa-user-tie'></i> Author": author.md
- "<i class='fa fa-file-contract'></i> License": license.md
