# BBQ task configuration for path aliases and script aliases.
paths:
  bp_root: "~/nsh/biology-problems/problems"
  qti_package_maker: "~/nsh/qti_package_maker"
  matching_sets: "{bp_root}/matching_sets"
  multiple_choice_statements: "{bp_root}/multiple_choice_statements"

script_aliases:
  YMATCH:
    - "{matching_sets}/yaml_match_to_bbq.py"
    - "{matching_sets}/yaml_which_one_mc_to_bbq.py"
  YMCS: "{multiple_choice_statements}/yaml_multiple_choice_statements.py"
  YMMS: "{matching_sets}/yaml_make_match_sets.py"
